# These are supported funding model platforms

github: Anisan
custom: ["https://boosty.to/Mboard","https://boosty.to/osyshome","https://yoomoney.ru/fundraise/13RKQDO87TR.240708","https://t.me/tribute/app?startapp=donation_17482"]
