# -*- coding: utf-8 -*-
"""Application configuration."""
import logging
import os
import re
import secrets
import yaml
from pathlib import Path
from datetime import timedelta

_logger = logging.getLogger('configuration')

# Значение secret_key из sample_config.yaml (синхронизируйте при изменении образца).
_SAMPLE_SECRET_KEY_FALLBACK = 'your-secret-key-here'


def _format_yaml_scalar(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, str):
        return f"'{value}'"
    return str(value)


def _replace_yaml_line_key(line, key, value, *, eol_comment=None):
    """Заменяет скаляр на строке вида '  key: old # note', сохраняя отступ."""
    newline = ''
    body = line
    if line.endswith('\r\n'):
        newline = '\r\n'
        body = line[:-2]
    elif line.endswith('\n'):
        newline = '\n'
        body = line[:-1]

    match = re.match(rf'^(\s*{re.escape(key)}:\s*)(.*)$', body)
    if not match:
        return line

    prefix, rest = match.group(1), match.group(2)
    existing_eol = ''
    for sep in ('  #', ' #'):
        idx = rest.find(sep)
        if idx != -1:
            existing_eol = rest[idx:]
            break

    if eol_comment is not None:
        suffix = f'  {eol_comment}' if eol_comment else existing_eol
    else:
        suffix = existing_eol

    return f"{prefix}{_format_yaml_scalar(value)}{suffix}{newline}"


def patch_config_yaml_preserving_comments(content, new_secret):
    """Точечно обновляет известные ключи безопасности, сохраняя комментарии файла."""
    lines = content.splitlines(keepends=True)
    if not lines and content:
        lines = [content]

    section = None
    subsection = None
    out = []
    debug_tool_keys = {
        'enabled', 'template_editor_enabled', 'profiler_enabled',
        'intercept_redirects', 'sqlalchemy_record_queries',
    }

    for line in lines:
        stripped = line.lstrip()
        if not stripped or stripped.startswith('#'):
            out.append(line)
            continue

        indent = len(line) - len(stripped)
        key_match = re.match(r'^([a-z_][a-z0-9_]*):\s*(.*)$', stripped)

        if indent == 0 and key_match:
            section = key_match.group(1)
            subsection = None
            out.append(line)
            continue

        if not key_match:
            out.append(line)
            continue

        key = key_match.group(1)

        if section == 'application' and indent == 2:
            if key == 'rate_limit':
                subsection = 'rate_limit'
                out.append(line)
                continue
            subsection = None
            if key == 'secret_key':
                out.append(_replace_yaml_line_key(
                    line, key, new_secret,
                    eol_comment='# auto-generated by osysHome (was sample default)',
                ))
                continue
            if key == 'debug':
                out.append(_replace_yaml_line_key(line, key, False))
                continue
            if key == 'env':
                out.append(_replace_yaml_line_key(line, key, 'production'))
                continue
            if key == 'session_cookie_samesite':
                out.append(_replace_yaml_line_key(line, key, 'Lax'))
                continue

        if section == 'application' and subsection == 'rate_limit' and indent == 4:
            if key == 'enabled':
                out.append(_replace_yaml_line_key(line, key, True))
                continue

        if section == 'debug_tools' and indent == 2 and key in debug_tool_keys:
            out.append(_replace_yaml_line_key(line, key, False))
            continue

        out.append(line)

    return ''.join(out)


class ConfigLoader(object):
    def __init__(self):
        """Base configuration."""
        self.DEBUG = True
        self.SECRET_KEY = 'secret-key'
        current_dir = os.path.abspath(os.path.dirname(__file__))
        self.APP_DIR = os.path.dirname(current_dir)
        # Assets Management
        self.ASSETS_ROOT = '/static/assets'
        self.PLUGINS_FOLDER = os.path.abspath(os.path.join(self.APP_DIR, "plugins"))
        self.FILES_DIR = os.path.abspath(os.path.join(self.APP_DIR, 'files'))

        self.APP_PORT = 5000
        self.ENV = 'dev'

        self.DEFAULT_TIMEZONE = "Europe/Moscow"

        self.POOL_SIZE = 30  # Размер пула потоков
        self.POOL_MAX_SIZE = None  # Максимальный размер пула потоков (по умолчанию 5*POOL_SIZE)
        self.POOL_TIMEOUT_THRESHOLD = 60.0  # Порог таймаута задач в секундах
        self.BATCH_WRITER_FLUSH_INTERVAL = 0.5  # Интервал записи батча в секундах

        # DB settings
        self.SQLALCHEMY_ECHO = False  # SQL log
        DB_NAME = 'app.db'
        # Put the db file in project root
        DB_PATH = os.path.join(self.APP_DIR, DB_NAME)
        self.SQLALCHEMY_DATABASE_URI = 'sqlite:///{0}'.format(DB_PATH)
        self.SQLALCHEMY_POOL_SIZE = 20  # Пул потоков для выполнения запросов к БД
        self.SQLALCHEMY_RECORD_QUERIES = False

        self.CACHE_FILE_PATH = "cache"  # Замените на путь к вашей папке кеша
        self.CACHE_DEFAULT_TIMEOUT = 300

        self.CACHE_TYPE = 'simple'  # Can be "memcached", "redis", etc.
        self.JWT_ACCESS_TOKEN_EXPIRES = timedelta(10 ** 6)

        # Session lifetime (default 31 days, same as Flask default)
        self.SESSION_LIFETIME_DAYS = 31
        self.PERMANENT_SESSION_LIFETIME = timedelta(days=31)

        # Session cookie security (production)
        self.SESSION_COOKIE_SECURE = False
        self.SESSION_COOKIE_SAMESITE = 'Lax'

        # Rate limiting
        self.RATELIMIT_ENABLED = True
        self.RATELIMIT_DEFAULT = '100 per minute'
        self.RATELIMIT_LOGIN = '5 per minute'
        self.RATELIMIT_API = '100 per minute'

        # HTTP requests timeout (seconds) - used by requests.get/post/etc
        self.HTTP_REQUEST_TIMEOUT = 15

        # Service name systemd
        self.SERVICE_NAME = None  # None or 'service_name'
        self.SERVICE_AUTORESTART = False
        self.SERVICE_DOCKER_CONTAINER = None  # None or 'container_name'

        # Debug tools
        self.DEBUG_TOOLS_ENABLED = False
        self.DEBUG_TB_TEMPLATE_EDITOR_ENABLED = False
        self.DEBUG_TB_PROFILER_ENABLED = False
        self.DEBUG_TB_PROFILER_DUMP_FILENAME = 'dump.prof'
        self.DEBUG_TB_INTERCEPT_REDIRECTS = False

        # True, если при загрузке применены рекомендуемые параметры безопасности.
        self.SECURITY_DEFAULTS_APPLIED = False

    @staticmethod
    def _read_sample_secret_key(app_dir):
        """Читает secret_key по умолчанию из sample_config.yaml."""
        sample_path = Path(app_dir) / 'sample_config.yaml'
        if not sample_path.is_file():
            return _SAMPLE_SECRET_KEY_FALLBACK
        try:
            with open(sample_path, 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f) or {}
            return (data.get('application') or {}).get('secret_key', _SAMPLE_SECRET_KEY_FALLBACK)
        except (yaml.YAMLError, OSError) as ex:
            _logger.warning("Cannot read sample_config.yaml for secret_key: %s", ex)
            return _SAMPLE_SECRET_KEY_FALLBACK

    def _apply_recommended_security_defaults(self, config_path):
        """Рекомендуемые параметры, если secret_key не меняли с образца."""
        new_secret = secrets.token_hex(32)

        self.SECRET_KEY = new_secret
        self.DEBUG = False
        self.ENV = 'production'
        self.SESSION_COOKIE_SAMESITE = 'Lax'
        self.SESSION_COOKIE_SECURE = False
        self.RATELIMIT_ENABLED = True
        self.RATELIMIT_DEFAULT = '100 per minute'
        self.RATELIMIT_LOGIN = '5 per minute'
        self.RATELIMIT_API = '100 per minute'
        self.DEBUG_TOOLS_ENABLED = False
        self.DEBUG_TB_TEMPLATE_EDITOR_ENABLED = False
        self.DEBUG_TB_PROFILER_ENABLED = False
        self.DEBUG_TB_INTERCEPT_REDIRECTS = False
        self.SQLALCHEMY_RECORD_QUERIES = False

        self.SECURITY_DEFAULTS_APPLIED = True
        self._persist_recommended_security_defaults(config_path, new_secret)

        _logger.warning(
            "secret_key matches sample_config.yaml — applied recommended security "
            "settings and generated a new secret_key (saved to %s). "
            "Review config.yaml and keep secret_key private.",
            config_path,
        )

    def _persist_recommended_security_defaults(self, config_path, new_secret):
        """Сохраняет автонастройку в config.yaml, сохраняя комментарии (без ruamel.yaml)."""
        config_path = Path(config_path)

        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                original = f.read()
        except OSError as ex:
            _logger.error("Failed to read config for security defaults: %s", ex)
            return

        try:
            patched = patch_config_yaml_preserving_comments(original, new_secret)
            with open(config_path, 'w', encoding='utf-8') as f:
                f.write(patched)
        except OSError as ex:
            _logger.error("Failed to persist security defaults to %s: %s", config_path, ex)

    def load_from_file(self, config_file):
        """Загружает конфигурацию из YAML файла."""
        config_path = Path(config_file)

        if not config_path.exists():
            raise FileNotFoundError(
                f"Configuration file {config_file} not found. "
                f"Please copy sample_config.yaml to {config_file} and configure it."
            )

        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                self._config_data = yaml.safe_load(f)
        except yaml.YAMLError as e:
            raise ValueError(f"Error parsing YAML configuration: {e}")

        app_config = self._config_data.get('application', {})
        self.DEFAULT_LANGUAGE = app_config.get('default_language', 'en')
        self.DEFAULT_TIMEZONE = app_config.get('default_timezone', 'Europe/Moscow')
        self.SECRET_KEY = app_config.get('secret_key', 'secret-key')
        self.DEBUG = app_config.get('debug', False)
        self.APP_PORT = app_config.get('app_port', 5000)
        self.ENV = app_config.get('env', 'dev')
        self.POOL_SIZE = app_config.get('pool_size', 20)
        self.POOL_MAX_SIZE = app_config.get('pool_max_size', None)
        self.POOL_TIMEOUT_THRESHOLD = app_config.get('pool_timeout_threshold', 60.0)
        self.BATCH_WRITER_FLUSH_INTERVAL = app_config.get('batch_writer_flush_interval', 0.5)

        # Session lifetime configuration
        self.SESSION_LIFETIME_DAYS = app_config.get('session_lifetime_days', 31)
        self.PERMANENT_SESSION_LIFETIME = timedelta(days=self.SESSION_LIFETIME_DAYS)

        # Session cookie security
        if not self.DEBUG:
            # По умолчанию НЕ принуждаем Secure, если явно не задано в конфиге
            self.SESSION_COOKIE_SECURE = app_config.get('session_cookie_secure', False)
            self.SESSION_COOKIE_SAMESITE = app_config.get('session_cookie_samesite', 'Lax')
        else:
            # В режиме debug поведение остаётся тем же
            self.SESSION_COOKIE_SECURE = app_config.get('session_cookie_secure', False)
            self.SESSION_COOKIE_SAMESITE = app_config.get('session_cookie_samesite', 'Lax')

        # Rate limiting
        rate_limit = app_config.get('rate_limit', {}) or {}
        self.RATELIMIT_ENABLED = rate_limit.get('enabled', True)
        default_limit = rate_limit.get('default', '100 per minute')
        self.RATELIMIT_DEFAULT = default_limit if self.RATELIMIT_ENABLED else []
        self.RATELIMIT_LOGIN = rate_limit.get('login', '5 per minute')
        self.RATELIMIT_API = rate_limit.get('api', '100 per minute')

        self.HTTP_REQUEST_TIMEOUT = app_config.get('http_request_timeout', 15)

        db_config = self._config_data.get('database', {})
        self.SQLALCHEMY_ECHO = db_config.get('sqlalchemy_echo', False)
        self.SQLALCHEMY_POOL_SIZE = db_config.get('pool_size', 20)
        if 'connection_string' in db_config:
            self.SQLALCHEMY_DATABASE_URI = db_config['connection_string']
        else:
            DB_NAME = db_config.get('db_name', 'app.db')
            DB_PATH = os.path.join(self.APP_DIR, DB_NAME)
            self.SQLALCHEMY_DATABASE_URI = f'sqlite:///{DB_PATH}'

        debug_tools_config = self._config_data.get('debug_tools', {})
        self.DEBUG_TOOLS_ENABLED = debug_tools_config.get('enabled', False)
        self.DEBUG_TB_TEMPLATE_EDITOR_ENABLED = debug_tools_config.get('template_editor_enabled', False)
        self.DEBUG_TB_PROFILER_ENABLED = debug_tools_config.get('profiler_enabled', False)
        self.DEBUG_TB_PROFILER_DUMP_FILENAME = debug_tools_config.get('profiler_dump_filename', 'dump.prof')
        self.DEBUG_TB_INTERCEPT_REDIRECTS = debug_tools_config.get('intercept_redirects', False)
        self.SQLALCHEMY_RECORD_QUERIES = debug_tools_config.get('sqlalchemy_record_queries', False)

        cache_config = self._config_data.get('cache', {})
        self.CACHE_FILE_PATH = os.path.abspath(os.path.join(self.APP_DIR, cache_config.get('file_path', 'cache')))
        self.CACHE_TYPE = cache_config.get('type', 'simple')
        self.CACHE_DEFAULT_TIMEOUT = cache_config.get('timeout', 300)

        service_config = self._config_data.get('service', {})
        self.SERVICE_AUTORESTART = service_config.get('autorestart', False)
        self.SERVICE_NAME = service_config.get('name', None)
        self.SERVICE_DOCKER_CONTAINER = service_config.get('docker_container', None)

        sample_secret = self._read_sample_secret_key(self.APP_DIR)
        if self.SECRET_KEY == sample_secret:
            self._apply_recommended_security_defaults(config_path)


def load_config(config_file='config.yaml'):
    """Удобная функция для загрузки конфигурации."""
    loader = ConfigLoader()
    loader.load_from_file(config_file)
    return loader


Config = load_config('config.yaml')
